[pytest]
# Пути к папкам с тестами
testpaths = tests

# Поиск файлов с тестами
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

# Параметры запуска по умолчанию
addopts =
    -s
    -v
    --strict-markers
    --tb=short
    --alluredir=./allure-results